upstream security {
    server localhost:8080;
}

upstream uploader {
    server localhost:3000;
}

upstream minio {
    server localhost:9000;
}

server {
    listen 80;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /auth {
        proxy_pass http://security/v1/token/validation;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Authorization $http_authorization;
        proxy_set_header X-Original-URI $request_uri;
    }

    location /register {
        proxy_pass http://security/v1/user;
    }

    location /token {
        proxy_pass http://security/v1/token;
    }

    location /user {
        auth_request /auth;
        auth_request_set $user_id $upstream_http_x_user_id;
        proxy_set_header X-User-Id $user_id;
        proxy_pass http://security/v1/user;
    }

    location /upload {
        auth_request /auth;
        auth_request_set $user_id $upstream_http_x_user_id;
        proxy_set_header X-User-Id $user_id;
        proxy_pass http://uploader/v1/upload;
    }

    location /images/ {
        auth_request /auth;
        auth_request_set $user_id $upstream_http_x_user_id;
        proxy_set_header X-User-Id $user_id;
        proxy_pass http://minio/images/;
    }
}