upstream security {
    server localhost:8080;
}

upstream uploader {
    server localhost:3000;
}

upstream minio {
    server localhost:9000;
}

server {
    location /auth {
        proxy_pass http://security/v1/token/validation;
    }

    location /register {
        proxy_pass http://security/v1/user;
    }

    location /token {
        proxy_pass http://security/v1/token;
    }

    location /user {
        auth_request /auth;
        proxy_pass http://security/v1/user;
    }

    location /upload {
        auth_request /auth;
        proxy_pass http://uploader/v1/upload;
    }

    location /images/ {
        auth_request /auth;
        proxy_pass http://minio/images/;
    }
}